//! Build script: embeds the application icon + version info into the Windows
//! executable. The icon itself is rendered at build time by the zero-dependency
//! `src/icon.rs`, so no binary asset needs to be committed for the embedded
//! resource. On machines without a resource compiler (rc.exe / windres) the
//! build still succeeds — we emit a `cargo:warning` and skip embedding.
//!
//! The locale half follows ADR-0008: it generates the i18n static tables from
//! `locales/*.toml`, treating `locales/zh-CN.toml` as the single source of truth
//! for the *key set*. A missing or extra key in `en-US.toml` **fails the build**
//! instead of shipping a half-translated UI. The format is deliberately trivial
//! (flat `key = "value"` lines; the only escapes used are `\t` and `\\`, which
//! TOML and Rust spell identically), so we parse it with `str::lines()` rather
//! than adding a TOML parser to the build-dependency tree for two files we
//! maintain ourselves.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[path = "src/icon.rs"]
mod icon;

/// Icon sizes embedded into the executable (a classic multi-resolution set).
const ICON_SIZES: [u32; 9] = [16, 20, 24, 32, 40, 48, 64, 128, 256];

/// 键集合的事实来源，与必须与之完全一致的那个语言。
const LOCALE_KEYS: &str = "zh-CN";
const LOCALE_MIRROR: &str = "en-US";

/// 解析一个扁平 locale 文件成 `(key, value)`，按 key 排序。
///
/// 生成物里的 `KEYS` 因此是有序的，`tr()` 可以直接二分查找（O(log n)、零分配）。
fn parse_locale(path: &Path) -> Vec<(String, String)> {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("读 locale 文件 {} 失败: {e}", path.display()));
    let mut out: Vec<(String, String)> = Vec::new();
    for (lineno, line) in raw.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line.split_once('=').unwrap_or_else(|| {
            panic!(
                "{}:{}: 不是 `\"key\" = \"value\"` 形式: {line}",
                path.display(),
                lineno + 1
            )
        });
        // 键是**带引号的**字面量键（`"tray.open_settings" = "打开设置"`）。
        // 必须加引号：TOML 会把裸的 `tray.open_settings = …` 解析成嵌套表
        // `[tray]` 下的 `open_settings`，而本项目的键里带点分隔符，
        // 依赖方（测试与文档）要的是一张**扁平**的 `键 → 字符串` 表。
        let key = key.trim();
        let key = key
            .strip_prefix('"')
            .and_then(|k| k.strip_suffix('"'))
            .unwrap_or_else(|| {
                panic!(
                    "{}:{}: 键必须写成带引号的字面量键（`\"{key}\"`）—— 裸键里的点会被 \
                     TOML 当成嵌套表分隔符: {key}",
                    path.display(),
                    lineno + 1
                )
            })
            .to_owned();
        let value = value.trim();
        let Some(body) = value.strip_prefix('"').and_then(|v| v.strip_suffix('"')) else {
            panic!(
                "{}:{}: 值必须是被双引号包起来的单行字符串: {value}",
                path.display(),
                lineno + 1
            );
        };
        // 值被**原样**搬进 Rust 字符串字面量。TOML 与 Rust 对 `\t` `\\` `\"` `\n`
        // 的解读一致，所以逐字复制是安全的；但裸 `"` 会提前结束字面量，必须挡在
        // 这里（写 locale 时用 `\"` 转义即可）。
        if body.replace("\\\"", "").contains('"') {
            panic!(
                "{}:{}: 值内部有未转义的 `\"`（生成物是 Rust 源码）: {body}",
                path.display(),
                lineno + 1
            );
        }
        if out.iter().any(|(k, _)| *k == key) {
            panic!("{}: 键 {key} 重复定义", path.display());
        }
        out.push((key, body.to_owned()));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

/// 校验两个 locale 的键集合完全一致，并生成 `$OUT_DIR/i18n.rs`。
fn generate_i18n(out_dir: &Path) {
    let keys = parse_locale(
        Path::new("locales")
            .join(format!("{LOCALE_KEYS}.toml"))
            .as_path(),
    );
    let mirror = parse_locale(
        Path::new("locales")
            .join(format!("{LOCALE_MIRROR}.toml"))
            .as_path(),
    );

    assert!(
        !keys.is_empty(),
        "locales/{LOCALE_KEYS}.toml 一个键都没有——它是非空性检查的唯一依据"
    );
    let missing: Vec<&str> = keys
        .iter()
        .map(|(k, _)| k.as_str())
        .filter(|k| !mirror.iter().any(|(o, _)| o == k))
        .collect();
    assert!(
        missing.is_empty(),
        "locales/{LOCALE_MIRROR}.toml 缺 {LOCALE_KEYS} 的 {} 个键（build.rs 是键集合的守门人）: {missing:?}",
        missing.len()
    );
    let extra: Vec<&str> = mirror
        .iter()
        .map(|(k, _)| k.as_str())
        .filter(|k| !keys.iter().any(|(s, _)| s == k))
        .collect();
    assert!(
        extra.is_empty(),
        "locales/{LOCALE_MIRROR}.toml 多出 {LOCALE_KEYS} 没有的 {} 个键: {extra:?}",
        extra.len()
    );

    let mut out = String::from(
        "// @generated by build.rs from locales/*.toml —— 请勿手改。\n\
         // 键集合以 locales/zh-CN.toml 为准；两个语言不一致时构建失败。\n\n",
    );
    out.push_str(&format!("pub const KEY_COUNT: usize = {};\n\n", keys.len()));
    // KEYS 放键本身，ZH_CN / EN_US 放**取值**——三个数组同序，第 i 项指同一条文案
    for (name, table, values) in [
        ("KEYS", &keys, false),
        ("ZH_CN", &keys, true),
        ("EN_US", &mirror, true),
    ] {
        out.push_str(&format!("pub static {name}: [&str; KEY_COUNT] = [\n"));
        for (k, v) in table.iter() {
            let cell = if values { v } else { k };
            out.push_str(&format!("    {cell:?},\n"));
        }
        out.push_str("];\n\n");
    }
    let path = out_dir.join("i18n.rs");
    fs::write(&path, out).unwrap_or_else(|e| panic!("写 {} 失败: {e}", path.display()));
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/icon.rs");
    println!("cargo:rerun-if-changed=locales/zh-CN.toml");
    println!("cargo:rerun-if-changed=locales/en-US.toml");

    let out_dir = env::var("OUT_DIR").ok().map(PathBuf::from);
    // i18n 表是纯数据，与目标平台无关，先于平台判断生成。
    if let Some(d) = &out_dir {
        generate_i18n(d);
    }

    // Resources only make sense for Windows targets (cross-compiles included).
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    // 1. Render the multi-size icon into $OUT_DIR/eyeflow.ico.
    let out_dir = match out_dir {
        Some(d) => d,
        None => {
            println!(
                "cargo:warning=EyeFlow build script: OUT_DIR not set; skipping resource embedding."
            );
            return;
        }
    };
    let ico_path = out_dir.join("eyeflow.ico");
    if let Err(e) = fs::write(&ico_path, icon::encode_ico(&ICON_SIZES)) {
        println!(
            "cargo:warning=EyeFlow build script: failed to write {} ({e}); skipping resource embedding.",
            ico_path.display()
        );
        return;
    }

    // 2. Compile the resource (icon + version info). winresource picks rc.exe
    //    for MSVC and windres for the GNU toolchain. Failure is non-fatal.
    let mut res = winresource::WindowsResource::new();
    res.set_icon(ico_path.to_string_lossy().as_ref());
    res.set("FileDescription", "EyeFlow 护眼提醒");
    res.set("ProductName", "EyeFlow");
    res.set("CompanyName", "lexingtonhibiki");
    res.set(
        "LegalCopyright",
        "Copyright (c) 2026 lexingtonhibiki. MIT License.",
    );
    res.set("OriginalFilename", "eyeflow.exe");
    res.set("InternalName", "eyeflow");
    // FileVersion / ProductVersion default to CARGO_PKG_VERSION inside winresource.

    if let Err(e) = res.compile() {
        println!(
            "cargo:warning=EyeFlow: could not embed Windows resources (icon/version info); \
             the executable will be built without them. \
             Typical cause: no resource compiler (rc.exe from the MSVC SDK, or windres from \
             MinGW binutils) found on PATH. Underlying error: {e}"
        );
    }
}
